### ISSUE TITLE
Releasing pretrained model weights?

### ISSUE THREAD

**Issue by dmckee5** [amunozgarza/mvt-gan#4]
Hello,

Thank you for this work and releasing your code! I was wondering if you plan to release any of the pretrained models as well (in particular, the UCF101 one)? Since it seems training is fairly long and compute intensive it would be a great help.

**Comment by mkumar10** [comment]
+1

**Comment by amunozgarza** [comment]
We are still experimenting with this architecture, in the next month or two we'll be done and as soon as that happens I will release what we know it is the final model.

**Comment by TalalWasim** [comment]
Hi,

Is there any plan to release the checkpoints?
